#!/usr/bin/env zsh

# Put this in your zsh config (ex: ~/.zshrc)

command_not_found_handler() {
    echo "Querying..."
    # Find which package contains the file
    package_name=$(dnf provides -q "*bin/$1" 2> /dev/null | sed 1q | awk '{print $1}')

    # If no package is found output the error message which ZSH shows by default
    [[ -z "$package_name" ]] && echo "zsh: command not found: $1" && exit 1

    # Notify user and ask whether or not they want to install the package
    echo -e "Command '\e[1m$1\e[0m' not found, but was found in the '\e[1m$package_name\e[0m' package."
    echo -n "Would you like to install it? [Y/n] "
    read -k confirm
    echo "\n" 

    [[ "$confirm" == [yY] ]] && sudo dnf install "$package_name"
}

